// Code generated by goctl. DO NOT EDIT.
// Source: miner.proto

package minerclient

import (
	"context"

	"github.com/haoshuwei/micro/miner/miner"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	MinerReq  = miner.MinerReq
	MinerResp = miner.MinerResp

	Miner interface {
		Min(ctx context.Context, in *MinerReq, opts ...grpc.CallOption) (*MinerResp, error)
	}

	defaultMiner struct {
		cli zrpc.Client
	}
)

func NewMiner(cli zrpc.Client) Miner {
	return &defaultMiner{
		cli: cli,
	}
}

func (m *defaultMiner) Min(ctx context.Context, in *MinerReq, opts ...grpc.CallOption) (*MinerResp, error) {
	client := miner.NewMinerClient(m.cli.Conn())
	return client.Min(ctx, in, opts...)
}
