// Code generated by goctl. DO NOT EDIT.
// Source: adder.proto

package adderclient

import (
	"context"

	"github.com/haoshuwei/micro/adder/protoc/adder"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddReq  = adder.AddReq
	AddResp = adder.AddResp

	Adder interface {
		Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
	}

	defaultAdder struct {
		cli zrpc.Client
	}
)

func NewAdder(cli zrpc.Client) Adder {
	return &defaultAdder{
		cli: cli,
	}
}

func (m *defaultAdder) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	client := adder.NewAdderClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
