// Code generated by goctl. DO NOT EDIT.
// Source: miner.proto

package server

import (
	"context"

	"github.com/haoshuwei/micro/miner/internal/logic"
	"github.com/haoshuwei/micro/miner/internal/svc"
	"github.com/haoshuwei/micro/miner/miner"
)

type MinerServer struct {
	svcCtx *svc.ServiceContext
	miner.UnimplementedMinerServer
}

func NewMinerServer(svcCtx *svc.ServiceContext) *MinerServer {
	return &MinerServer{
		svcCtx: svcCtx,
	}
}

func (s *MinerServer) Min(ctx context.Context, in *miner.MinerReq) (*miner.MinerResp, error) {
	l := logic.NewMinLogic(ctx, s.svcCtx)
	return l.Min(in)
}
