// Code generated by goctl. DO NOT EDIT.
// Source: adder.proto

package server

import (
	"context"

	"github.com/haoshuwei/micro/adder/adder"
	"github.com/haoshuwei/micro/adder/internal/logic"
	"github.com/haoshuwei/micro/adder/internal/svc"
)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	adder.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) Add(ctx context.Context, in *adder.AddReq) (*adder.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
